//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeTouch.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeTouch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 tools\platform-tools_r29.0.5-windows\platform-tools\adb.exe 的本地化字符串。
        /// </summary>
        internal static string AdbFile {
            get {
                return ResourceManager.GetString("AdbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个基于 Android 调试桥实现的，可以辅助完成 的本地化字符串。
        /// </summary>
        internal static string CommentPart1 {
            get {
                return ResourceManager.GetString("CommentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安卓手机上特殊操作的程序 的本地化字符串。
        /// </summary>
        internal static string CommentPart2 {
            get {
                return ResourceManager.GetString("CommentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (C) 2020 Li Guanglin 的本地化字符串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tools\platform-tools_r29.0.5-windows.zip 的本地化字符串。
        /// </summary>
        internal static string PlatformToolsPackage {
            get {
                return ResourceManager.GetString("PlatformToolsPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tools 的本地化字符串。
        /// </summary>
        internal static string ToolsDirectory {
            get {
                return ResourceManager.GetString("ToolsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 1.6.2 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tools\window_dump.xml 的本地化字符串。
        /// </summary>
        internal static string WindowDumpFile {
            get {
                return ResourceManager.GetString("WindowDumpFile", resourceCulture);
            }
        }
    }
}
